spring:
  datasource:
    url: jdbc:mysql://localhost:3307/oj_dev?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: ojtest
    password: 123456
    hikari:
      minimum-idle: 5 #最⼩空闲连接数
      maximum-pool-size: 20 #最⼤连接数
      idle-timeout: 30000 #空闲连接存活时间（毫秒）
      connection-timeout: 30000 #连接超时时间（毫秒）